inherits = "base"

[palette]
# Light -> Dark
shade-1 = "#f2f2f2"
shade-2 = "#cccccc"
shade-3 = "#999999"
shade-4 = "#666666"
shade-5 = "#4d4d4d"
shade-6 = "#333333"
shade-7 = "#1a1a1a"
shade-8 = "#0d0d0d"

# Highlights
hl = "#73b6e6"
secondary-hl = "#cfdce6"

# Pallete
blue = "#73b6e6"
green = "#b6e673"
red = "#e67373"
yellow = "#e6bf73"
