inherits = "base"

[palette]
# Dark -> Light
shade-1 = "#0d0d0d"
shade-2 = "#262626"
shade-3 = "#666666"
shade-4 = "#808080"
shade-5 = "#bfbfbf"
shade-6 = "#d9d9d9"
shade-7 = "#e6e6e6"
shade-8 = "#f2f2f2"

# Highlights
hl = "#0061a6"
secondary-hl = "#73b4e6"

# Pallete
blue = "#0061a6"
green = "#61a600"
red = "#a60000"
yellow = "#a66f00"
