theme = "lua"

[editor]
color-modes = true
completion-timeout = 5
completion-trigger-len = 1
continue-comments = false
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.lsp]
goto-reference-include-declaration = false

[keys.normal]
A-w = "move_next_sub_word_start"
A-e = "move_next_sub_word_end"
A-b = "move_prev_sub_word_start"
X = "extend_line_above"
"*" = "search_selection"
"A-*" = "search_selection_detect_word_boundaries"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.select]
A-w = "extend_next_sub_word_start"
A-e = "extend_next_sub_word_end"
A-b = "extend_prev_sub_word_start"
X = "extend_line_above"
"*" = "search_selection"
"A-*" = "search_selection_detect_word_boundaries"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
e = "file_explorer_in_current_buffer_directory"
E = "file_explorer_in_current_directory"

[keys.normal.g]
C-d = ["vsplit", "jump_view_up", "goto_definition"]
C-S-d = ["vsplit", "jump_view_up", "goto_declaration"]
C-y = ["vsplit", "jump_view_up", "goto_type_definition"]
C-i = ["vsplit", "jump_view_up", "goto_implementation"]

[keys.insert]
"A-;" = "flip_selections"
S-tab = "move_parent_node_start"


[keys.normal.ret]
e = [
  ':sh rm -f /tmp/yazi-chooser-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-chooser-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/yazi-chooser-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
