#!/usr/bin/env bash

NVIM_DIR="$HOME/.config/nvim"
NIX_DIR="$(git rev-parse --show-toplevel)/home/nvim/lazy"

no_commit=false
direction=""

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --no-commit) no_commit=true ;;
        nix|nvim|diff) direction="$1" ;;
        --help)
            echo "Usage: $0 [--no-commit] {nix|nvim|diff}"
            echo
            echo "This script syncs configuration files for LazyVim between your Neovim config directory and a nix store directory."
            echo
            echo "Options:"
            echo "  nix              Syncs from the Neovim config to the nix store and optionally commits."
            echo "  nvim             Syncs from the nix store to the Neovim config directory."
            echo "  diff             Displays differences between files in the Neovim config and the nix store."
            echo "  --no-commit      Copy files without creating a git commit."
            echo "  --help           Display this help message."
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--no-commit] {nix|nvim|diff}"
            exit 1
            ;;
    esac
    shift
done

if [[ -z "$direction" ]]; then
    echo "Usage: $0 [--no-commit] {nix|nvim|diff}"
    exit 1
fi

# Define the source and destination based on direction
if [[ "$direction" == "nix" ]]; then
    SRC_DIR="$NVIM_DIR"
    DST_DIR="$NIX_DIR"
elif [[ "$direction" == "nvim" ]]; then
    SRC_DIR="$NIX_DIR"
    DST_DIR="$NVIM_DIR"
elif [[ "$direction" == "diff" ]]; then
    git diff --no-index "$NIX_DIR/lazy-lock.json" "$NVIM_DIR/lazy-lock.json"
    git diff --no-index "$NIX_DIR/lazyvim.json" "$NVIM_DIR/lazyvim.json"
    exit 0
else
    echo "Invalid direction. Use 'nix', 'nvim', or 'diff'."
    exit 1
fi

cp --no-preserve=all "$SRC_DIR/lazy-lock.json" "$DST_DIR/lazy-lock.json"
cp --no-preserve=all "$SRC_DIR/lazyvim.json" "$DST_DIR/lazyvim.json"
echo "Files copied from $SRC_DIR to $DST_DIR."

if [[ "$direction" == "nix" && "$no_commit" == false ]]; then
    if git diff --quiet "$NIX_DIR"; then
        echo "No changes to sync."
    else
        git commit "$NIX_DIR" -m "nvim: sync lazy"
        echo "Changes committed to git."
    fi
fi
