format = """
$directory\
$cmd_duration\
$status\
$git_branch\
$nix_shell\
$line_break\
$character\
"""

[directory]
style = "blue"
truncate_to_repo = false
read_only = "[RO]"

[character]
success_symbol = "[❯](bright-white)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
format = "[\\[$branch(:$remote_branch)\\]]($style) "
style = "purple"

[nix_shell]
format = "[\\[$name\\]]($style) "
style = "bright-black"

[status]
format = "[$status]($style) "
disabled = false
map_symbol = true
