# C/C++
[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[language-server.clangd]
args = [
  "--query-driver=**",
  "--header-insertion=never",
  "--clang-tidy",
  "--background-index",
]

# Nix
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

# Python
[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

# SQL
[[language]]
name = "sql"
auto-format = true
formatter = { command = "pg_format", args = ["-"] }

# TOML
[[language]]
name = "toml"
auto-format = true

# Typst
[[language]]
name = "typst"
auto-format = true

[language-server.tinymist.config]
formatterMode = "typstyle"
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
]

# Rust
[language-servers.rust-analyzer.config]
cargo.features = "all"
cargo.targetDir = true
files.exclude = [".git", ".jj", "target"]

# Web
[[language]]
name = "css"
auto-format = true
language-servers = [
  { name = "vscode-css-language-server", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
]

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "jsonc"
auto-format = true
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
auto-format = true
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome"]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "vtsls", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
]

[language-server.biome]
command = "npx"
args = ["biome", "lsp-proxy"]

[language-server.vtsls]
command = "npx"
args = ["vtsls", "--stdio"]

[language-server.vtsls.config]
hostInfo = "helix"
typescript.inlayHints.enumMemberValues.enabled = true
typescript.inlayHints.functionLikeReturnTypes.enabled = true
typescript.inlayHints.parameterNames.enabled = "literals"
typescript.inlayHints.parameterTypes.enabled = true
typescript.inlayHints.propertyDeclarationTypes.enabled = true
typescript.inlayHints.variableTypes.enabled = true
typescript.updateImportsOnFileMove.enabled = "always"
vtsls.autoUseWorkspaceTsdk = true
vtsls.experimental.maxInlayHintLength = 30

[language-server.vscode-css-language-server]
command = "npx"
args = ["vscode-css-language-server", "--stdio"]

[language-server.vscode-html-language-server]
command = "npx"
args = ["vscode-html-language-server", "--stdio"]

[language-server.vscode-json-language-server]
command = "npx"
args = ["vscode-json-language-server", "--stdio"]

[language-server.tailwindcss-ls]
command = "npx"
args = ["tailwindcss-language-server", "--stdio"]
