# C/C++
[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[language-server.clangd]
args = [
  "--query-driver=**",
  "--header-insertion=never",
  "--clang-tidy",
  "--background-index",
]

# Lua
[[language]]
name = "lua"
auto-format = true

[language-server.lua-language-server.config.Lua.format]
defaultConfig.indent_style = "space"
defaultConfig.indent_size = 2

# Nix
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

# Python
[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

# SQL
[[language]]
name = "sql"
auto-format = true
formatter = { command = "pg_format", args = ["-"] }

# TOML
[[language]]
name = "toml"
auto-format = true

# Typst
[[language]]
name = "typst"
auto-format = true

[language-server.tinymist.config]
formatterMode = "typstyle"
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
]

# Rust
[language-servers.rust-analyzer.config]
cargo.features = "all"
cargo.targetDir = true
check.command = "clippy"
files.exclude = [".git", ".jj", "target"]

# Web
[[language]]
name = "css"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }
language-servers = ["vtsls"]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }
language-servers = ["vtsls"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }
language-servers = ["vtsls"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettierd", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }
language-servers = ["vtsls"]

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config]
hostInfo = "helix"
typescript.inlayHints.enumMemberValues.enabled = true
typescript.inlayHints.functionLikeReturnTypes.enabled = true
typescript.inlayHints.parameterNames.enabled = "literals"
typescript.inlayHints.parameterTypes.enabled = true
typescript.inlayHints.propertyDeclarationTypes.enabled = true
typescript.inlayHints.variableTypes.enabled = true
typescript.updateImportsOnFileMove.enabled = "always"
vtsls.autoUseWorkspaceTsdk = true
vtsls.experimental.maxInlayHintLength = 30
