inherits = "base"

[palette]
# Dark -> Light
shade-1 = "#000000"
shade-2 = "#121212"
shade-3 = "#212121"
shade-4 = "#323232"
shade-5 = "#535353"
shade-6 = "#737373"
shade-7 = "#949494"
shade-8 = "#b4b4b4"
shade-9 = "#d5d5d5"
shade-10 = "#f5f5f5"

# Highlights
hl = "#0061a6"
secondary-hl = "#002d4d"

# Diff
delta = "#0061a6"
minus = "#a60000"
plus = "#61a600"

# Diagnostics
error = "#a60000"
hint = "#0061a6"
info = "#0061a6"
warning = "#a66f00"
